// Bridges a placed consumer order to the driver dashboard through the
// Python/FastAPI backend (backend/, POST /orders) — the server validates the
// delivery location again, computes the item summary, inserts the shared
// `orders` row, and alerts the drivers. This stays a one-way, best-effort
// side-effect: it never throws, so a missing backend or a network failure can
// never break checkout.
import type { Address, CartLine } from '../types';
import { API_URL, isBackendConfigured } from './api';

/** True only when EXPO_PUBLIC_API_URL is set — mirrors the old edge-function gate. */
export const isDispatchConfigured = isBackendConfigured;

export interface DispatchOrderInput {
  /** Generated by placeOrder before payment: the row's primary key, and the id
   *  stamped into the PaymentIntent metadata. Passing it in (rather than
   *  minting one here) is what makes a dispatch retry idempotent. */
  orderId: string;
  /** The Stripe intent that paid for this order. Null in demo mode. The
   *  backend refuses the order without it whenever payments are configured. */
  paymentIntentID: string | null;
  lines: CartLine[];
  subtotal: number;
  deliveryFee: number;
  tip: number;
  total: number;
  restaurantName: string;
  restaurantAddress: string;
  customerName: string;
  deliveryAddress: Address | null;
  /** Supabase Auth uid of the customer placing the order, so a driver who
   *  accepts it can be tied back to this account for the "on its way" message.
   *  Null when the consumer isn't signed in against the backend. */
  customerId: string | null;
}

/**
 * One attempt at publishing. Returns the order id, or null on any failure.
 * Swallows all errors — the caller's local order record is the source of truth.
 */
async function attemptPublish(
  input: DispatchOrderInput,
): Promise<string | null> {
  if (!API_URL) return null;

  const { lines, deliveryAddress } = input;

  const dropoff = [deliveryAddress?.addressLine, deliveryAddress?.apartmentSuite]
    .filter((part) => part && part.trim().length > 0)
    .join(', ');

  const id = input.orderId;

  try {
    const res = await fetch(`${API_URL}/orders`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        id,
        payment_intent_id: input.paymentIntentID,
        restaurant_name: input.restaurantName,
        restaurant_address: input.restaurantAddress,
        customer_name: input.customerName,
        customer_id: input.customerId,
        dropoff_address: dropoff,
        latitude: deliveryAddress?.latitude ?? 0,
        longitude: deliveryAddress?.longitude ?? 0,
        subtotal: input.subtotal,
        delivery_fee: input.deliveryFee,
        tip: input.tip,
        total: input.total,
        items: lines.map((l) => ({ name: l.item.name, quantity: l.quantity })),
      }),
    });
    if (!res.ok) {
      const text = await res.text().catch(() => '');
      console.warn('[dispatch] order publish failed:', res.status, text.slice(0, 200));
      return null;
    }
    return id;
  } catch (err) {
    console.warn('[dispatch] order publish threw:', err);
    return null;
  }
}

/**
 * Publishes a placed order, retrying a few times with backoff.
 *
 * The retries exist because this now runs *after* the customer's card has been
 * charged: a transient network blip here would otherwise mean paid money and
 * no order on any driver's screen. The backend keys off the client-generated
 * id and reports a repeat as a duplicate success, so retrying is safe.
 */
export async function publishOrderToDispatch(
  input: DispatchOrderInput,
): Promise<string | null> {
  const delaysMs = [0, 800, 2500];
  for (const delay of delaysMs) {
    if (delay > 0) await new Promise((resolve) => setTimeout(resolve, delay));
    const id = await attemptPublish(input);
    if (id) return id;
  }
  console.warn('[dispatch] giving up after retries for order', input.orderId);
  return null;
}
